### ISSUE TITLE
New Update Breaks functionality

### ISSUE THREAD

**Issue by Aaron-Pool** [adrianlee44/atom-aligner#68] opened 2017-05-17 15:19 UTC
Just downloaded the most recent update, and nothing happens upon running alignment. My specific use case is assignment operation are not being aligned. Please see the link below for demonstration.

https://i.gyazo.com/c1e54a445427cda5dddad9585374cf5c.mp4

**Comment by dwelle** [comment] 2017-05-17 19:45
meanwhile, we can downgrade via ` apm install aligner@0.22.3` (that's the last version that works for me).

**Comment by adrianlee44** [comment] 2017-05-18 06:59
Any chance you have https://atom.io/packages/aligner-javascript installed?

**Comment by adrianlee44** [comment] 2017-05-18 08:33
Aligner v1+ removed the basic set of configurations and opted for language specific configurations. I thought I have added code to prompt user to install `aligner-javascript` but it seems like it wasn't working as I expected.

I have since fixed the issue with v1.2.0 and should now prompt you to install `aligner-javascript`. Hope this fixes the problem you were having.

**Comment by dwelle** [comment] 2017-05-18 09:55
Yep, didn't notify before and now it does, and works properly. You still need to restart atom to be notified of the required dependency (not sure if it can be fixed).

**Comment by Aaron-Pool** [comment] 2017-05-19 17:34
Ok, so that worked, and the package is now semi-functional. But the object-colon alignment setting doesn't seem to work anymore. No matter whether the box is checked or unchecked it still puts the space on the right side of the colon.

**Comment by adrianlee44** [comment] 2017-05-20 05:05
Working on reproducing the issue.

Are you trying to convert
```javascript
let test = {
  hello: 'world',
  a: 'test',
  aVeryLongString: 'orMaybeNot',
}
```

to
```javascript
let test = {
  hello          : 'world',
  a              : 'test',
  aVeryLongString: 'orMaybeNot',
}
```

or

```javascript
let test = {
  hello:           'world',
  a:               'test',
  aVeryLongString: 'orMaybeNot',
}
```

**Comment by Aaron-Pool** [comment] 2017-05-20 19:41
First one :)

Btw, thank you so much for being so on the ball about this!

**Comment by Aaron-Pool** [comment] 2017-05-20 19:43
OH NEVER MIND. I take back everything I said, I was using the settings on the original atom-package and I assumed that `:-leftspace` check box must be what I was looking for. I found the right setting on the new jaavscript-aligner package and everything is working fine.

**Comment by adrianlee44** [comment] 2017-05-21 07:08
No worries. I'm glad you figured it out and it's working for you. Wasn't expecting the settings to linger in the `aligner` package. Might look into a way to clean that up.

**Comment by azawawi** [comment] 2017-05-21 07:18
@adrianlee44 Thanks for all your excellent work. I am having the same problem since the new release with [atom-aligner-python](https://github.com/adrianlee44/atom-aligner-python). Can you please check it out? Even a normal `=` alignment is not working without a downgrade.

**Comment by adrianlee44** [comment] 2017-05-21 07:19
Can you file an issue on atom-aligner-python with a code sample you are trying to align? Thanks

**Comment by azawawi** [comment] 2017-05-21 07:19
Sure

**Comment by adrianlee44** [comment] 2017-05-23 06:06
Looks like most of the issues are now resolved with the new update. I'm going to close this issue. Please let me know if there are still issues.

**Closed by adrianlee44** 2017-05-23 06:06 UTC

**Comment by Aaron-Pool** [comment] 2017-05-24 17:30
Thanks again @adrianlee44 ! This package fulfills all my hyper-perfectionist impulses, and I really appreciate you being so quick in getting any problems addressed.

Keep up the good work 👍

**Comment by azawawi** [comment] 2017-05-24 21:55
@adrianlee44 Thanks for your excellent package. I use it everyday 👍
