### ISSUE TITLE
Can't get it to work with LiveScript

### ISSUE THREAD

**Issue by Industrial** [adrianlee44/atom-aligner#53] opened 2016-03-30 22:55 UTC
Hi!

I'm mainly coding in [LiveScript](http://livescript.net) these days and I have one problem:

Alignment of `{ x, y } = z` does not work.

```
gulp-plumber     = require \gulp-plumber
gulp-spawn-mocha = require \gulp-spawn-mocha
handle-error     = require \../lib/handle-error
{ some, things, here } = require \thing
```

**Comment by adrianlee44** [comment] 2016-03-31 03:19
Do you use any additional language package for LiveScript?

**Comment by Industrial** [comment] 2016-04-04 08:09
Yes, I use https://atom.io/packages/language-livescript

**Comment by adrianlee44** [comment] 2016-04-05 07:40
For clarification, you are looking for the `=` in `{ x, y } = z` to align with previous `=`s, right?

**Comment by Industrial** [comment] 2016-04-05 09:44
Yes, that would be great :-)

**Comment by adrianlee44** [comment] 2016-04-07 07:47
The issue is with the grammar. Currently the grammar is parsing `} =` as one token instead of 2. I'll look into creating a PR for that grammar.

**Comment by adrianlee44** [comment] 2016-04-07 07:52
It also seems like the package is not maintained for a while now so creating a PR might not fix this issue.

**Comment by Industrial** [comment] 2016-04-07 08:11
Okay, I will look into continuing/owning that package this weekend :-)

**Comment by adrianlee44** [comment] 2016-04-07 08:13
Let me know if you do as I have a quick patch for the grammar.

I'm going to close this for now.

**Closed by adrianlee44** 2016-04-07 08:13 UTC
